# Generated by Django 6.1.1 on 2026-10-05 17:03

from typing import Any

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def mark_existing_processed(apps: Any, schema_editor: Any) -> None:
    Flip = apps.get_model("api", "Flip")
    Flip.objects.filter(processed__isnull=False).update(
        notification_state="claimed", next_evaluation=None
    )
    for flip in (
        Flip.objects.filter(processed=None, reason="timeout")
        .select_related("owner")
        .iterator()
    ):
        flip.incident_grace = flip.owner.grace
        flip.grace_start = flip.created - flip.owner.grace
        flip.save(update_fields=("incident_grace", "grace_start"))


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0123_alter_channel_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="check",
            name="last_success",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="check",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="api.check",
            ),
        ),
        migrations.AddField(
            model_name="check",
            name="up_since",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="flip",
            name="grace_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flip",
            name="incident_grace",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flip",
            name="next_evaluation",
            field=models.DateTimeField(
                blank=True, db_index=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="flip",
            name="notification_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Unknown"),
                    ("timeout", "Timeout"),
                    ("fail", "Fail signal"),
                ],
                default="",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="flip",
            name="notification_state",
            field=models.CharField(
                choices=[
                    ("ready", "Ready"),
                    ("waiting", "Waiting for parents"),
                    ("resuming", "Recovery grace"),
                    ("claimed", "Claimed"),
                    ("cancelled", "Cancelled"),
                ],
                default="ready",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="flip",
            name="resume_after",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flip",
            name="resume_signature",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(mark_existing_processed, migrations.RunPython.noop),
    ]
